### ISSUE TITLE
As developer, I want to use the auth server tokens to authenticate the users, so that I can use the API.

### ISSUE THREAD

**Issue by ricardobrg** [mytiki/dashboard#55]
### Acceptance Criteria

- [ ] Frontend REST API client that handles the authentication with auth server
- [ ] Login redirection of unauthenticated users
- [ ] The API uses the token

### Tasks

Frontend
- [ ] #61
- [x] #62
- [ ] #63
- [x] #68 
- [x] #69 

API
- [ ] Configure the endpoints with IAM authentication
